AllCops:
  TargetRubyVersion: 2.6.3

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 180

Metrics/MethodLength:
  Max: 15

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Lint/AmbiguousBlockAssociation:
  Enabled: false

Naming:
  Enabled: false

Style/IfInsideElse:
  Enabled: false
